# Site settings
title: crimps - Developer
description: "..."
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "http://crimps.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https:yourusername.githu.io'
# User settings
username: crimps
user_title: crimps - FrontEnd
email: 
twitter_username: 
github_username:  crimps
gplus_username:  
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: leetcode
    url: https://github.com/crimps/leetCode
  - name: 
    url: https://github.com/
  - name: 
    url: https://github.com/ 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
